[package]
name = "restful_api_test"
version = "0.1.0"
edition = "2024"
default-run = "teacher_service"
[dependencies]
actix-web = "4.12.1"
chrono = { version = "0.4.42", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }


[[bin]]
name = "teacher_service"
